function QTGAdminGun:AddKillIcon(a,b)
	killicon.Add(a,b,Color(255,80,0))
end
QTGAdminGun:AddKillIcon('qtg_admin_gun','Neptune_QTG/weapons/killicon/qtg_admin_gun/Default')
QTGAdminGun:AddKillIcon('qtg_ent_bullet','Neptune_QTG/weapons/killicon/qtg_admin_gun/Default')
QTGAdminGun:AddKillIcon('qtg_explosion','Neptune_QTG/weapons/killicon/qtg_admin_gun/explosion')
QTGAdminGun:AddKillIcon('qtg_nuke_explosion','Neptune_QTG/weapons/killicon/qtg_admin_gun/Nuke')
QTGAdminGun:AddKillIcon('qtg_grenade_ar2','Neptune_QTG/weapons/killicon/qtg_admin_gun/grenade')
QTGAdminGun:AddKillIcon('qtg_grenade_frag','Neptune_QTG/weapons/killicon/qtg_admin_gun/grenade_frag')
QTGAdminGun:AddKillIcon('qtg_universal_kill','Neptune_QTG/weapons/killicon/qtg_admin_gun/universal_kill')